
public class FibonocciSumEven {

	public static void main(String[] args) {
		
		long a=0;
		long b=1;
		long c;
		long sum=0;
		//System.out.println(""+a+""+b);
		
		/*for(long i=2;i<4000000;++i ){
			
			//System.out.println(""+a+""+b);
			c=a+b;
			System.out.print( "  "+c);
			//if(c%2==0)
				//sum+=c;
			
			//System.out.println(""+sum);
			
			b=c;
			a=b;
			
			
			
		}
		*/
		
		while(true){
			
			c=a+b;
			
			a=b;
			b=c;
			if(c>4000000){
				
				break;
			}
				
				if(c%2==0){
					//System.out.println(""+c);
					sum+=c;
					}
				
			
			
			
			
		}
		
		
		System.out.println(""+sum);

	}

}
/* 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
